CREATE TABLE IF NOT EXISTS candles (
 id INTEGER PRIMARY KEY,
 symbol TEXT NOT NULL,
 timestamp TEXT NOT NULL,
 open REAL NOT NULL,
 high REAL NOT NULL,
 low REAL NOT NULL,
 close REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS signals (
 id INTEGER PRIMARY KEY,
 symbol TEXT NOT NULL,
 timestamp TEXT NOT NULL,
 side TEXT NOT NULL,
 entry REAL NOT NULL,
 stop REAL NOT NULL,
 tp1 REAL NOT NULL,
 tp2 REAL NOT NULL
);
CREATE TABLE IF NOT EXISTS trades (
 id INTEGER PRIMARY KEY,
 signal_id INTEGER,
 side TEXT NOT NULL,
 entry REAL NOT NULL,
 exit REAL,
 lots REAL NOT NULL,
 pnl REAL,
 reason TEXT
);
CREATE TABLE IF NOT EXISTS risk_limits (
 id INTEGER PRIMARY KEY,
 risk_per_trade REAL NOT NULL DEFAULT 0.0025,
 max_daily_loss REAL NOT NULL DEFAULT 0.005,
 max_lot REAL NOT NULL DEFAULT 0.01
);
